language: go

install:
  - sudo apt-get install hugo

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  target_branch: master
  github_token: $GITHUB_TOKEN
  keep_history: true
  fqdn: www.n4h.party
  on:
    branch: source
