baseURL = "https://www.n4h.party"
languageCode = "zh-cn"
title = "N4H"
theme = "hermit"
description = "Let's Party Hard!"
hasCJKLanguage = true

[author]
  name = "N4H"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  
  themeColor = "#494f5c"
  homeSubtitle = "Let's Party Hard."
  justifyContent = false
  relatedPosts = false

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 20
